# Generated by Django 4.2 on 2023-06-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_remove_course_vide_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type_course',
            field=models.CharField(choices=[('free', 'free'), ('Pro', 'Pro')], default='free', max_length=30),
        ),
    ]
