# Generated by Django 4.2 on 2023-06-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_lessons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='lesson',
            new_name='course',
        ),
    ]
