# Generated by Django 4.2 on 2023-06-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_lessons_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
