# Generated by Django 4.2 on 2023-06-10 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0014_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 6, 10, 2, 49, 39, 780622, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
