# Generated by Django 4.2 on 2023-06-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_course_upload_date_alter_course_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='upload_date',
            field=models.DateField(),
        ),
    ]
