# Generated by Django 4.2 on 2023-06-10 23:31

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_alter_course_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
