# Generated by Django 4.2 on 2023-06-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_alter_lessons_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='video_url',
            field=models.CharField(max_length=1000),
        ),
    ]
