# Generated by Django 4.2.2 on 2023-06-12 05:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0020_alter_lessons_lesson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='lesson_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
