# Generated by Django 4.2 on 2023-06-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0022_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='preview',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=30),
        ),
    ]
