# Generated by Django 4.2 on 2023-06-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0024_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
