# Generated by Django 4.2.2 on 2023-06-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0026_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='course_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='lesson_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
