# Generated by Django 4.2.2 on 2023-06-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0027_notes_course_name_notes_lesson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_free_lessons',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
