# Generated by Django 4.2.2 on 2023-06-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0028_course_total_free_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='free_count_lessons',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=30),
        ),
    ]
