# Generated by Django 4.2.2 on 2023-06-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0030_alter_course_total_free_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='new_course',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
    ]
